/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {


        String word = args[0];

        //take first char and move to end add way
        char first = word.charAt(0);
        String result = word.substring(1) + " " + first + "ay";

        System.out.println(result);
    }
}
